apiVersion: v1
kind: Service
metadata:
  name: mongodb-legacy-redirect
  namespace: alphacar
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mongodb
  # [핵심] 백엔드가 찾는 옛날 IP를 여기에 등록하여 트래픽을 가로챕니다.
  externalIPs:
  - 192.168.0.201
